services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./src/mongodb_data:/data/db
      - ./src/mongodb_data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
